blogTitle = "koddsson.com/blog"
linkPrefix = "/blog"

authorName = "Kristján Oddsson"
authorTwitterUsername = "koddsson"
authorLocation = "London"
authorBuilding = "the <a href='https://cloudflare.com'>Cloudflare</a> dashboard."